services:
  frontend:
    image: node:22-alpine
    container_name: react-vite-frontend
    volumes:
      - ./frontend:/frontend
      - ./frontend/src:/frontend/src
      - /frontend/node_modules
    working_dir: /frontend
    ports:
      - "3008:3008"
    command: sh -c "npm install && npm run dev -- --host" #--host être visible sur le port
    environment:
      - CHOKIDAR_USEPOLLING=true #Prend en compte les changement
    networks:
      - backend-frontend

  backend:
    image: python:3.10
    container_name: django-backend
    #env_file: backend/.env # Fichier contenant les variables d'environnement comme DATABASE_URL
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    working_dir: /code
    networks:
      - backend-frontend
      - backend-db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-db

networks:
  backend-db:
  backend-frontend:

volumes:
  postgres_data:
  node_modules:
